//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shot {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Shot.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        internal static string RecordingStartLabel {
            get {
                return ResourceManager.GetString("RecordingStartLabel", resourceCulture);
            }
        }
        
        internal static string RecordingPauseLabel {
            get {
                return ResourceManager.GetString("RecordingPauseLabel", resourceCulture);
            }
        }
        
        internal static string RecordingResumeLabel {
            get {
                return ResourceManager.GetString("RecordingResumeLabel", resourceCulture);
            }
        }
        
        internal static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        internal static string RecordingsListText {
            get {
                return ResourceManager.GetString("RecordingsListText", resourceCulture);
            }
        }
        
        internal static string PlayText {
            get {
                return ResourceManager.GetString("PlayText", resourceCulture);
            }
        }
        
        internal static string StopText {
            get {
                return ResourceManager.GetString("StopText", resourceCulture);
            }
        }
        
        internal static string SaveRecordingLabel {
            get {
                return ResourceManager.GetString("SaveRecordingLabel", resourceCulture);
            }
        }
        
        internal static string EnterNameLabel {
            get {
                return ResourceManager.GetString("EnterNameLabel", resourceCulture);
            }
        }
        
        internal static string RecordingsListTitle {
            get {
                return ResourceManager.GetString("RecordingsListTitle", resourceCulture);
            }
        }
    }
}
